# Generated by Django 5.1.1 on 2024-10-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cedula',
            field=models.CharField(default='9999999999999', max_length=13),
        ),
    ]
