# Generated by Django 5.1.1 on 2024-11-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
    ]
