# Generated by Django 5.1.1 on 2024-10-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_habitacion', models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('suite', 'Suite')], max_length=10)),
                ('precio_habitacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_habitacion', models.IntegerField(unique=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'habitaciones_habitaciones',
            },
        ),
    ]
