# Generated by Django 5.1.1 on 2024-11-08 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0002_alter_reserva_cedula'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
                ('servicio_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicioextra')),
            ],
        ),
    ]
